# Generated by Django 5.2.17 on 2026-08-15 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'), ('view_leaderboard', 'Can view the corp score leaderboard'), ('view_breakdown', "Can view other members' full score breakdown (hard pull)"), ('manage_settings', 'Can manage CorpScore settings'), ('trigger_recompute', 'Can trigger a score recompute')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, default='fas fa-medal', max_length=64)),
                ('rule', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('component', models.CharField(blank=True, default='', max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpscore_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='main', max_length=64, unique=True)),
                ('weight_alliance_fat', models.PositiveIntegerField(default=30)),
                ('weight_corp_fat', models.PositiveIntegerField(default=25)),
                ('weight_activity', models.PositiveIntegerField(default=15)),
                ('weight_corptools', models.PositiveIntegerField(default=10)),
                ('weight_discord', models.PositiveIntegerField(default=10)),
                ('weight_srp', models.PositiveIntegerField(default=10)),
                ('decay_window_alliance_fat', models.PositiveIntegerField(default=90)),
                ('decay_window_corp_fat', models.PositiveIntegerField(default=90)),
                ('decay_window_activity', models.PositiveIntegerField(default=180)),
                ('decay_window_discord', models.PositiveIntegerField(default=30)),
                ('tier_subprime', models.PositiveIntegerField(default=300)),
                ('tier_fair', models.PositiveIntegerField(default=580)),
                ('tier_prime', models.PositiveIntegerField(default=670)),
                ('tier_elite', models.PositiveIntegerField(default=740)),
                ('tier_blackcard', models.PositiveIntegerField(default=800)),
                ('group_gating_enabled', models.BooleanField(default=False)),
                ('recompute_interval_hours', models.PositiveIntegerField(default=24)),
                ('log_hard_inquiries', models.BooleanField(default=True)),
                ('hard_inquiry_penalty', models.PositiveIntegerField(default=2)),
                ('hard_inquiry_penalty_window_days', models.PositiveIntegerField(default=30)),
                ('hard_inquiry_penalty_max', models.PositiveIntegerField(default=10)),
                ('last_recomputed_at', models.DateTimeField(blank=True, null=True)),
                ('elite_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corpscore_elite', to='auth.group')),
                ('subprime_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corpscore_subprime', to='auth.group')),
            ],
            options={
                'verbose_name': 'CorpScore settings',
                'verbose_name_plural': 'CorpScore settings',
            },
        ),
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('tier', models.CharField(choices=[('subprime', 'Subprime Capsuleer'), ('fair', 'Fair Weather Pilot'), ('prime', 'Prime Member'), ('elite', 'Elite Capsuleer'), ('blackcard', 'Black Card / Concord-Verified')], max_length=16)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(default='scheduled', help_text='What triggered this recompute: scheduled, import, manual, signal.', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpscore_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreComponentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=32)),
                ('raw_value', models.FloatField(default=0)),
                ('raw_unit', models.CharField(blank=True, default='', max_length=32)),
                ('normalised', models.FloatField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('points', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='aa_corpscore.scoresnapshot')),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='HardInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('pulled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corpscore_hard_inquiries_made', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpscore_hard_inquiries_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pulled_at'],
                'indexes': [models.Index(fields=['subject', '-pulled_at'], name='aa_corpscor_subject_66081c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa_corpscore.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpscore_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.AddIndex(
            model_name='scoresnapshot',
            index=models.Index(fields=['user', '-computed_at'], name='aa_corpscor_user_id_e148ed_idx'),
        ),
    ]
