# Generated by Django 5.2.17 on 2026-08-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_corpscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresettings',
            name='decay_window_pvp',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='weight_pvp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='zkill_enabled',
            field=models.BooleanField(default=False, help_text='Enable zKillboard PvP data as a score component. When off, the PvP adapter is skipped regardless of weight.'),
        ),
    ]
