# Generated by Django 5.2.17 on 2026-08-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_corpscore', '0002_scoresettings_decay_window_pvp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordActivityDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_uid', models.BigIntegerField(db_index=True)),
                ('date', models.DateField()),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('voice_minutes', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Discord activity (daily)',
                'verbose_name_plural': 'Discord activity (daily)',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['discord_uid', '-date'], name='aa_corpscor_discord_331231_idx')],
                'unique_together': {('discord_uid', 'date')},
            },
        ),
    ]
