# Generated by Django 5.2.17 on 2026-08-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_corpscore', '0003_discordactivitydaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_enabled',
            field=models.BooleanField(default=False, help_text="Enable ShipFinance integration. When on, the member's CorpScore tier affects their interest rate, insurance premium, and eligibility for finance/rentals."),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_insurance_adj_blackcard',
            field=models.DecimalField(decimal_places=2, default=-1.0, help_text='Insurance premium adjustment for Black Card.', max_digits=5),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_insurance_adj_elite',
            field=models.DecimalField(decimal_places=2, default=-0.5, help_text='Insurance premium adjustment for Elite Capsuleer.', max_digits=5),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_insurance_adj_fair',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Insurance premium adjustment for Fair Weather Pilot.', max_digits=5),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_insurance_adj_prime',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Insurance premium adjustment for Prime Member (baseline).', max_digits=5),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_insurance_adj_subprime',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Insurance premium adjustment for Subprime.', max_digits=5),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_min_score_finance',
            field=models.PositiveIntegerField(default=0, help_text='Members below this score cannot finance ships. 0 = no minimum.'),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_min_score_rent',
            field=models.PositiveIntegerField(default=0, help_text='Members below this score cannot rent ships. 0 = no minimum.'),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_rate_adj_blackcard',
            field=models.DecimalField(decimal_places=2, default=-3.0, help_text='Interest rate adjustment for Black Card (best discount).', max_digits=5),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_rate_adj_elite',
            field=models.DecimalField(decimal_places=2, default=-1.5, help_text='Interest rate adjustment for Elite Capsuleer (discount).', max_digits=5),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_rate_adj_fair',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Interest rate adjustment for Fair Weather Pilot.', max_digits=5),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_rate_adj_prime',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Interest rate adjustment for Prime Member (baseline).', max_digits=5),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='shipfinance_rate_adj_subprime',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Interest rate adjustment for Subprime (e.g. +5% added to base).', max_digits=5),
        ),
    ]
