# Generated by Django 5.2.17 on 2026-08-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_corpscore', '0004_scoresettings_shipfinance_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresettings',
            name='decay_window_industrypool',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='decay_window_memberstatus',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='weight_industrypool',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresettings',
            name='weight_memberstatus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
