# Generated by Django 5.2.17 on 2026-08-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_corpscore', '0005_scoresettings_decay_window_industrypool_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('view_leaderboard', 'Can view the corp score leaderboard'), ('view_breakdown', "Can view other members' full score breakdown (hard pull)"), ('manage_settings', 'Can manage CorpScore settings'), ('trigger_recompute', 'Can trigger a score recompute'), ('api_access', 'Can access CorpScore REST API endpoints'))},
        ),
    ]
